### ISSUE TITLE
Compiled application code crashes when developed as a part of RushJS monorepo and having Swagger CLI enabled.

### ISSUE THREAD

**Issue by artursudnik** [nestjs/swagger#1952]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When developing NestJS application with NestJS CLI plugin enabled and within RushJS mono repository, compiled code crashes with an error:

```
[Nest] 94062  - 06/27/2022, 3:17:20 PM     LOG [NestFactory] Starting Nest application...
[Nest] 94062  - 06/27/2022, 3:17:20 PM     LOG [InstanceLoader] AppModule dependencies initialized +14ms
node:internal/modules/cjs/loader:933
  const err = new Error(message);
              ^

Error: Cannot find module '.pnpm/@sphereon+pex@1.0.2/node_modules/@sphereon/pex/dist/main/lib/types/SSI.types'
Require stack:
- /Users/artur/nestjs-swaggercliplugin-rush-issue/apps/nestjs-app/dist/dtos/test1.dto.js
- /Users/artur/nestjs-swaggercliplugin-rush-issue/apps/nestjs-app/dist/app.controller.js
- /Users/artur/nestjs-swaggercliplugin-rush-issue/apps/nestjs-app/dist/app.module.js
- /Users/artur/nestjs-swaggercliplugin-rush-issue/apps/nestjs-app/dist/main.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Function._OPENAPI_METADATA_FACTORY (/Users/artur/nestjs-swaggercliplugin-rush-issue/apps/nestjs-app/dist/dtos/test1.dto.js:7:105)
    at ModelPropertiesAccessor.applyMetadataFactory (/Users/artur/nestjs-swaggercliplugin-rush-issue/common/temp/node_modules/.pnpm/@nestjs+swagger@5.2.1_d698c50e080e28585857283d96ea096d/node_modules/@nestjs/swagger/dist/services/model-properties-accessor.js:27:93)
    at SchemaObjectFactory.extractPropertiesFromType (/Users/artur/nestjs-swaggercliplugin-rush-issue/common/temp/node_modules/.pnpm/@nestjs+swagger@5.2.1_d698c50e080e28585857283d96ea096d/node_modules/@nestjs/swagger/dist/services/schema-object-factory.js:76:38)
    at SchemaObjectFactory.exploreModelSchema (/Users/artur/nestjs-swaggercliplugin-rush-issue/common/temp/node_modules/.pnpm/@nestjs+swagger@5.2.1_d698c50e080e28585857283d96ea096d/node_modules/@nestjs/swagger/dist/services/schema-object-factory.js:92:41)
    at /Users/artur/nestjs-swaggercliplugin-rush-issue/common/temp/node_modules/.pnpm/@nestjs+swagger@5.2.1_d698c50e080e28585857283d96ea096d/node_modules/@nestjs/swagger/dist/services/schema-object-factory.js:33:36
    at Array.map (<anonymous>) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/artur/nestjs-swaggercliplugin-rush-issue/apps/nestjs-app/dist/dtos/test1.dto.js',
    '/Users/artur/nestjs-swaggercliplugin-rush-issue/apps/nestjs-app/dist/app.controller.js',
    '/Users/artur/nestjs-swaggercliplugin-rush-issue/apps/nestjs-app/dist/app.module.js',
    '/Users/artur/nestjs-swaggercliplugin-rush-issue/apps/nestjs-app/dist/main.js'
  ]
}
```

The application starts as expected when starting it with `npm run start:dev`

### Minimum reproduction code

https://github.com/artursudnik/nestjs-swaggercliplugin-rush-issue

### Steps to reproduce

Clone the example code and then execute the following:

```
rush install
cd apps/nestjs-app
npm run build
node dist/main.js
```

### Expected behavior

I'd expect code to run without errors like it happens when executing it in developer mode `npm run start:dev`

### Package version

5.2.1

### NestJS version

8.4.7

### Node.js version

16.15.1

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [x] Linux

**Comment by kamilmysliwiec** [comment]
Please, report this issue in the RushJS repository.
