### ISSUE TITLE
Regular expression in Matches decorator of class-validator throws exception

### ISSUE THREAD

**Issue by RaiMX** [nestjs/swagger#1982]
### Did you read the migration guide?

- [X] I have read the whole migration guide

### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Describe the regression

When using regular expression in @Matches decorator from class-validator swagger throws exception

```bash
/app/node_modules/js-yaml/lib/dumper.js:868
      throw new YAMLException('unacceptable kind of an object to dump ' + type);
            ^
YAMLException: unacceptable kind of an object to dump [object RegExp]
    at writeNode (/app/node_modules/js-yaml/lib/dumper.js:868:13)
    at writeBlockMapping (/app/node_modules/js-yaml/lib/dumper.js:731:10)
    at writeNode (/app/node_modules/js-yaml/lib/dumper.js:834:9)
    at writeBlockMapping (/app/node_modules/js-yaml/lib/dumper.js:731:10)
    at writeNode (/app/node_modules/js-yaml/lib/dumper.js:834:9)
    at writeBlockMapping (/app/node_modules/js-yaml/lib/dumper.js:731:10)
    at writeNode (/app/node_modules/js-yaml/lib/dumper.js:834:9)
    at writeBlockMapping (/app/node_modules/js-yaml/lib/dumper.js:731:10)
    at writeNode (/app/node_modules/js-yaml/lib/dumper.js:834:9)
    at writeBlockMapping (/app/node_modules/js-yaml/lib/dumper.js:731:10)

```

### Minimum reproduction code

Have typeorm entity like this
```ts
import { Transform } from 'class-transformer';
import {
    IsAlphanumeric,
    IsNotEmpty,
    IsOptional,
    Matches,
} from 'class-validator';

@Entity()
export class DocPropTypes {
    @IsOptional({ groups: [CREATE] })
    @IsNotEmpty({ groups: [UPDATE] })
    @PrimaryGeneratedColumn()
    id: number;

    @IsNotEmpty({ groups: [CREATE] })
    @IsOptional({ groups: [UPDATE] })
    @IsAlphanumeric()
    @Matches(/[^ ]+/)  // <============== This line gives errors. Removing this line and exception is gone
    @Transform((transform) => transform.value?.trim())
    @Column({ comment: 'Code' })
    code: string;
}

```

### Expected behavior

With old swagger (nestjs 8) there was no error

**Comment by kamilmysliwiec** [comment]
We're tracking this here https://github.com/nestjs/swagger/pull/1980
