### ISSUE TITLE
Tutorial seems to be broken

### ISSUE THREAD

**Issue by ToKaTpoHb** [nestjs/swagger#20]
I'm having issues with initializing swagger module. 

My server.ts file:

```
import { NestFactory } from '@nestjs/core';
import { json } from 'body-parser';
import { ApplicationModule } from './modules/app.module';
import { SwaggerModule, DocumentBuilder } from '@nestjs/swagger';

async function bootstrap() {
  const app = await NestFactory.create(ApplicationModule);
  app.use(json());

  const options = new DocumentBuilder()
    .setTitle('Cats example')
    .setDescription('The cats API description')
    .setVersion('1.0')
    .addTag('cats')
    .build();
  const document = SwaggerModule.createDocument(app, options);
  SwaggerModule.setup('/api', app, document);

  await app.listen(3000);
}
bootstrap();
```

And i have following result:

```
[Nest] 2632   - 2017-12-6 19:38:42   [ExceptionHandler] app.use() requires a middleware function
TypeError: app.use() requires a middleware function
    at Function.use (D:\Learning\nest\project\node_modules\express\lib\application.js:210:11)
    at NestApplication.use (D:\Learning\nest\project\node_modules\@nestjs\core\nest-application.js:103:22)
    at exceptions_zone_1.ExceptionsZone.run (D:\Learning\nest\project\node_modules\@nestjs\core\nest-factory.js:107:48)
    at Function.run (D:\Learning\nest\project\node_modules\@nestjs\core\errors\exceptions-zone.js:16:13)
    at Proxy.args (D:\Learning\nest\project\node_modules\@nestjs\core\nest-factory.js:106:54)
    at Function.setup (D:\Learning\nest\project\node_modules\@nestjs\swagger\swagger-module.js:11:13)
    at D:\Learning\nest\project\server\server.ts:17:17
    at Generator.next (<anonymous>)
    at fulfilled (D:\Learning\nest\project\server\server.ts:4:58)
    at <anonymous>
(node:2632) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Unhandled Runtime Exception.
(node:2632) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero
 exit code.
```

Line 17 is where i call `SwaggerModule.setup('/api', app, document)`

**Comment by chymz** [comment]
Same problem here !

I've a workarround : 

```ts
import { NestFactory } from '@nestjs/core';
import * as express from 'express';
import * as SwaggerUI from 'swagger-ui-express';
import { SwaggerModule, DocumentBuilder } from '@nestjs/swagger';

async function bootstrap() {
  const server = express();
  const app = await NestFactory.create(ApplicationModule, server);

  const options = new DocumentBuilder()
    .setTitle('Sample API')
    .setDescription('Sample API')
    .setVersion('1.0')
    .addTag('sample-api')
    .build();
  const document = SwaggerModule.createDocument(app, options);

  // Here use express instance directly
  server.use('/api', SwaggerUI.serve, SwaggerUI.setup(document));

  await app.listen(3000);
}

bootstrap()
  .then(() => {
    console.log('Application is listening on port 3000');
  })
  .catch((err) => {
    console.error(err);
  });
```

**Comment by ToKaTpoHb** [comment]
Looks like it worked for me. Ty for help!

**Comment by ToKaTpoHb** [comment]
I have another problem with it. If i try to access "/api", it works great. But if i try something like "/api/users", it still shows me swagger ui.

**Comment by kamilmysliwiec** [comment]
@ToKaTpoHb I can't reproduce your issue. What version of nest are you using?

**Comment by ToKaTpoHb** [comment]
Here is my [package-lock.json](https://pastebin.com/HNhB5U0i).

**Comment by petebeegle** [comment]
@ToKaTpoHb 

> I have another problem with it. If i try to access "/api", it works great. But if i try something like "/api/users", it still shows me swagger ui.

I think that this is because you have set your swagger endpoint to the same value as setGlobalPrefix.

Try something like `server.use('/api/swagger', SwaggerUI.serve, SwaggerUI.setup(document));`.

**Comment by ToKaTpoHb** [comment]
@petebeegle 
Your sugguestion resolved issue, but i still wont to access swagger via '/api'. Probably, ill setup some redirects or something. I think, this case is worth to mention on tutorial page.
