### ISSUE TITLE
Error in Swagger with Firebase Cloud Function

### ISSUE THREAD

**Issue by kss943** [nestjs/swagger#222]
I have this code for creating firebase cloud function with Swagger :
```
import { NestFactory } from '@nestjs/core';
import { ApplicationModule } from './app.module';
import { 
  SwaggerModule, 
  DocumentBuilder } from '@nestjs/swagger';
import {
    NestExpressApplication,
    ExpressAdapter} from '@nestjs/platform-express'
import * as functions from 'firebase-functions';
import * as express from 'express';


const server = express();

const startNestApplication = async (expressInstance) => {
  const app = await NestFactory.create<NestExpressApplication>(
    ApplicationModule,
    new ExpressAdapter(expressInstance));

  const options = new DocumentBuilder()
    .setTitle('Title')
    .setDescription('Description')
    .setVersion('4.59')
    .build();

    const document = SwaggerModule.createDocument(app, options);
    SwaggerModule.setup('api', app, document);

  await app.init();
}


startNestApplication(server)

export const ExpressNestAPI = functions.https.onRequest(server);``
```
Without Swagger it work. But then i try to deploy it with SwaggerModule appear this error: 

```
(node:27668) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined

    at lodash_1.mapValues.param (/Users/student/Desktop/Project/functions/node_modules/@nestjs/swagger/dist/explorers/api-parameters.explorer.js:33:20)
    at /Users/student/Desktop/Project/functions/node_modules/lodash/lodash.js:13402:38
    at /Users/student/Desktop/Project/functions/node_modules/lodash/lodash.js:4911:15
    at baseForOwn (/Users/student/Desktop/Project/functions/node_modules/lodash/lodash.js:2996:24)
    at Function.mapValues (/Users/student/Desktop/Project/functions/node_modules/lodash/lodash.js:13401:7)
    at exploreApiReflectedParametersMetadata (/Users/student/Desktop/Project/functions/node_modules/@nestjs/swagger/dist/explorers/api-parameters.explorer.j
s:32:41)
    at exports.exploreApiParametersMetadata (/Users/student/Desktop/Project/functions/node_modules/@nestjs/swagger/dist/explorers/api-parameters.explorer.js
:10:33)
    at explorers.reduce (/Users/student/Desktop/Project/functions/node_modules/@nestjs/swagger/dist/swagger-explorer.js:55:45)
    at Array.reduce (<anonymous>)
    at lodash_1.mapValues (/Users/student/Desktop/Project/functions/node_modules/@nestjs/swagger/dist/swagger-explorer.js:54:97)
```

**Comment by kamilmysliwiec** [comment]
Please, provide a minimal repository which reproduces your issue.

**Comment by kss943** [comment]
That was issue for version 6.0.2 with swagger 2.
Now, I tried my code with version 6.5.2(swagger 3) and it work.
Please, write here if you still need minimal repository.
Thank you for answer!

**Comment by aruss** [comment]
I run following packages

  "@nestjs/common": "^6.5.3",
    "@nestjs/core": "^6.5.3",
    "@nestjs/platform-express": "^6.5.3",
    "@nestjs/swagger": "^3.1.0",
    "@nestjs/testing": "^6.5.3",
    "@nestjs/typeorm": "^6.1.3"

and as soon I add the swagger to the app I get this error.
