### ISSUE TITLE
Swagger build not work properly in monorepo front/back with shared module

### ISSUE THREAD

**Issue by NToularastel** [nestjs/swagger#2444]
### Is there an existing issue for this?

- [ ] I have searched the existing issues

### Current behavior

We use monorepo by pnpm, with angular on front side.
So, shared module build in es2020 and commonjs.

When project run (start:dev), this error appear :
```
export var Enumeration;
^^^^^^

SyntaxError: Unexpected token 'export'
    at internalCompileFunction (node:internal/vm:74:18)
    at wrapSafe (node:internal/modules/cjs/loader:1141:20)
    at Module._compile (node:internal/modules/cjs/loader:1182:27)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1272:10)
    at Module.load (node:internal/modules/cjs/loader:1081:32)
    at Function.Module._load (node:internal/modules/cjs/loader:922:12)
    at Module.require (node:internal/modules/cjs/loader:1105:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Function._OPENAPI_METADATA_FACTORY (C:\...\project\api\dist\models\...\dtos\some.dto.js:31:510)
    at ModelPropertiesAccessor.applyMetadataFactory (C:\...\project\node_modules\.pnpm\@nestjs+swagger@6.3.0_@nestjs+common@9.4.0_@nestjs+core@9.4.0_class-transformer@0.5.1_class-v_tawtoz62cnnknjwgt6qid3wlmm\node_modules\@nestjs\swagger\dist\services\model-properties-accessor.js:27:93)
```

_OPENAPI_METADATA_FACTORY function looks like :
```TS
static _OPENAPI_METADATA_FACTORY() {
        return { prop1: { required: true, type: () => String }, prop2: { required: true, type: () => String }, prop3: { required: false, enum: require("../../../common/enums/other-enum").OtherEnum}, prop4: { required: false, type: () => String }, prop5: { required: false, type: () => String }, prop6: { required: false, type: () => String }, prop7: { required: false, type: () => Boolean }, prop8: { required: false, type: () => Boolean }, prop9: { required: false, enum: require("../../../../../share/lib/mjs/models/enums/shared-enum").SharedEnum }, prop10: { required: false, type: () => String }, prop11: { required: false, type: () => String } };
    }
```

Note : prop9 imported by require on its file, instead of using import properly generated above
```TS
const share_1 = require("share");

prop9: { required: false, enum: require("../../../../../share/lib/mjs/models/enums/shared-enum").SharedEnum }
```

Import in code looks like :
```TS
import { SharedEnum } from 'share';

prop9: SharedEnum;
```

### Minimum reproduction code

https://github.com/NToularastel/reproduct-nestjs-swagger

### Steps to reproduce

1. `pnpm i`
2. `cd reproduct-nestjs-swagger`
3. `pnpm run --filter share build`
4. `pnpm run --filter api start:dev`
5. see error

### Expected behavior

We think that the build should use the correct import, generate by build, instead of reimporting.
Like this :
```TS
const share_1 = require("share");

prop9: { required: false, enum: share_1.SharedEnum }
```

### Package version

6.3.0

### NestJS version

9.4.0

### Node.js version

18.13.0

### In which operating systems have you tested?

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
