### ISSUE TITLE
`TypeError` when starting swagger with any class variable present in a controller. (v7)

### ISSUE THREAD

**Issue by submarines-and** [nestjs/swagger#2484]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When trying to start nest with swagger config enabled and any class variable in a controller, I get the error below.. It seems like the reflector is checking local class variables, and throwing a type error if it finds any. In the reproduction below, **I can remove `localVariable` and it starts working.**

```
TypeError on swagger startup

/Users/submarines/dev/hej/node_modules/reflect-metadata/Reflect.js:354
                throw new TypeError();
                      ^
TypeError: 
    at Reflect.getMetadata (/Users/submarines/dev/hej/node_modules/reflect-metadata/Reflect.js:354:23)
    at getStatusCode (/Users/submarines/dev/hej/node_modules/@nestjs/swagger/dist/explorers/api-response.explorer.js:41:28)
    at /Users/submarines/dev/hej/node_modules/@nestjs/swagger/dist/explorers/api-response.explorer.js:76:31
    at Array.forEach (<anonymous>)
    at applyMetadataFactory (/Users/submarines/dev/hej/node_modules/@nestjs/swagger/dist/explorers/api-response.explorer.js:70:20)
    at exploreApiResponseMetadata (/Users/submarines/dev/hej/node_modules/@nestjs/swagger/dist/explorers/api-response.explorer.js:25:5)
    at /Users/submarines/dev/hej/node_modules/@nestjs/swagger/dist/swagger-explorer.js:72:45
    at Array.reduce (<anonymous>)
    at /Users/submarines/dev/hej/node_modules/@nestjs/swagger/dist/swagger-explorer.js:71:104
    at /Users/submarines/dev/hej/node_modules/lodash/lodash.js:13469:38

```

### Minimum reproduction code
See below

### Steps to reproduce
```
import { Controller, Get, Module } from '@nestjs/common';
import { NestFactory } from '@nestjs/core';
import { FastifyAdapter, NestFastifyApplication } from '@nestjs/platform-fastify';
import { DocumentBuilder, SwaggerModule } from '@nestjs/swagger';
import { Observable, of } from 'rxjs';

@Controller('test')
export class TestController {

  /** If I remove this, it works */
  private localVariable = 1;

  @Get()
  public testFunction(): Observable<boolean> {
    return of(true);
  }

}

@Module({ controllers: [TestController] })
export class TestModule { }

export async function main(): Promise<void> {
  const app = await NestFactory.create<NestFastifyApplication>(TestModule, new FastifyAdapter());

  const config = new DocumentBuilder().build();
  SwaggerModule.setup('/api/swagger', app, SwaggerModule.createDocument(app, config));

  await app.listen(443, '0.0.0.0');
}

main();
```

### Expected behavior

Swagger should work

### Package version

7.0.0

### NestJS version

10.0.0

### Node.js version

18.12.1

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [x] Linux

**Comment by kamilmysliwiec** [comment]
Could you test with v7.0.1?

**Comment by submarines-and** [comment]
7.0.1 solves it, thank you!
