### ISSUE TITLE
Error "Cannot find module" when importing type from external module using CLI plugin

### ISSUE THREAD

**Issue by gjgomez** [nestjs/swagger#2700]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

I have a controller with a POST action that receives a body specified by a DTO class. The DTO class contains a property with a type that's defined in an external package/module. The app runs fine if issuing the `npm run start` command. 

However, if I register the CLI plugin (in the nest-cli.json file) to auto-generate metadata for the DTO model to be shown in the Swagger UI, the application errors out with the following error after issuing the `npm run start` command.

```
Error: Cannot find module 'class-transformer/types/enums/transformation-type.enum'
Require stack:
- /Users/ggomez/Code/research/nest-openapi-external-dep-test/dist/TestCreateRequest.dvo.js
- /Users/ggomez/Code/research/nest-openapi-external-dep-test/dist/test.controller.js
- /Users/ggomez/Code/research/nest-openapi-external-dep-test/dist/app.module.js
- /Users/ggomez/Code/research/nest-openapi-external-dep-test/dist/main.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Function._OPENAPI_METADATA_FACTORY (/Users/ggomez/Code/research/nest-openapi-external-dep-test/dist/TestCreateRequest.dvo.js:22:263)
    at ModelPropertiesAccessor.applyMetadataFactory (/Users/ggomez/Code/research/nest-openapi-external-dep-test/node_modules/@nestjs/swagger/dist/services/model-properties-accessor.js:27:93)
    at SchemaObjectFactory.extractPropertiesFromType (/Users/ggomez/Code/research/nest-openapi-external-dep-test/node_modules/@nestjs/swagger/dist/services/schema-object-factory.js:79:38)
    at SchemaObjectFactory.exploreModelSchema (/Users/ggomez/Code/research/nest-openapi-external-dep-test/node_modules/@nestjs/swagger/dist/services/schema-object-factory.js:103:41)
    at /Users/ggomez/Code/research/nest-openapi-external-dep-test/node_modules/@nestjs/swagger/dist/services/schema-object-factory.js:33:36
    at Array.map (<anonymous>)
```

### Minimum reproduction code

https://github.com/gjgomez/nestjs-openapi-external-dep-test

### Steps to reproduce

1. `git clone https://github.com/gjgomez/nestjs-openapi-external-dep-test.git`
2. `cd nestjs-openapi-external-dep-test`
3. `npm i`
4. `npm run start`

### Expected behavior

The expectation is that when using the NestJs CLI plugin and running the `npm run start` command, the NestJs application would compile and start successfully, and navigating to the `http://localhost:3000/api` endpoint would display the Swagger UI describing the `POST /test` endpoint with its corresponding schema, listing all properties with validation, description, and example attributes.

### Package version

7.1.15

### NestJS version

10.2.8

### Node.js version

16.13.1

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by kamilmysliwiec** [comment]
Same issue, different library https://github.com/nestjs/swagger/issues/1563
