### ISSUE TITLE
Error when swagger is used in a hybrid app

### ISSUE THREAD

**Issue by james7272** [nestjs/swagger#5]
The swagger module throws an error when used in a hybrid app.  Possibly because the microservice is marked as a controller but has no http methods?

```

TypeError: Cannot read property 'path' of undefined
    at lodash_1.groupBy (/home/james/projects/paladinjs/paladinjs-core/node_modules/@nestjs/swagger/swagger-transformer.js:6:83)
    at arrayAggregator (/home/james/projects/paladinjs/paladinjs-core/node_modules/lodash/lodash.js:518:34)
    at Function.groupBy (/home/james/projects/paladinjs/paladinjs-core/node_modules/lodash/lodash.js:4862:16)
    at SwaggerTransformer.normalizePaths (/home/james/projects/paladinjs/paladinjs-core/node_modules/@nestjs/swagger/swagger-transformer.js:6:40)
    at SwaggerScanner.scanApplication (/home/james/projects/paladinjs/paladinjs-core/node_modules/@nestjs/swagger/swagger-scanner.js:15:50)
    at Function.createDocument (/home/james/projects/paladinjs/paladinjs-core/node_modules/@nestjs/swagger/swagger-module.js:6:46)
    at Function.<anonymous> (/home/james/projects/paladinjs/paladinjs-core/dist/bin/paladin.js:45:53)
    at Generator.next (<anonymous>)
    at /home/james/projects/paladinjs/paladinjs-core/dist/bin/paladin.js:7:71
    at __awaiter (/home/james/projects/paladinjs/paladinjs-core/dist/bin/paladin.js:3:12)
    at Function.init (/home/james/projects/paladinjs/paladinjs-core/dist/bin/paladin.js:40:16)
    at /home/james/projects/paladinjs/paladinjs-core/dist/bin/startup.js:20:27
    at Generator.next (<anonymous>)
    at fulfilled (/home/james/projects/paladinjs/paladinjs-core/dist/bin/startup.js:4:58)
    at process._tickCallback (internal/process/next_tick.js:109:7)
    at Module.runMain (module.js:607:11)
    at run (bootstrap_node.js:427:7)
    at startup (bootstrap_node.js:151:9)
    at bootstrap_node.js:542:3

```
Here is how swagger is used.
``` javascript
        try {
            const documentBuilder = new DocumentBuilder();
            const doc = SwaggerModule.createDocument(app, documentBuilder.build());
            httpserver.use('/swagger', swaggerUI.serve, swaggerUI.setup(doc));
            httpserver.use('/api-docs', (req, res, next) => res.send(doc));
        } catch (error) {
            console.error(error);
        }

```
Here is the service

``` javascript
import { MessagePattern } from '@nestjs/microservices';
import { Controller, Inject } from '@nestjs/common';
import { LOGGER_TOKEN, ILogger } from '../logger/logger';
import { USER_STORE_TOKEN, UserStore } from './user-store';

import { GET_ORGS } from './user.service.proxy';

@Controller()
export class UsersService {

    constructor( @Inject(USER_STORE_TOKEN) private store: UserStore,
                 @Inject(LOGGER_TOKEN) private logger: ILogger) {
    }

    @MessagePattern(GET_ORGS)
    async getOrganisations() {
        let orgs = await this.store.getOrganisations();
        if (!orgs) {
            await this.store.addOrganisation('default');
            orgs = await this.store.getOrganisations();
        }
        return orgs;
    }
}

```

**Comment by kamilmysliwiec** [comment]
hi @james7272,
Unfortunately, I can't reproduce this issue, I'm pretty sure that I'm doing sth wrong. Could you share the repo?

**Comment by james7272** [comment]
Hi Kamil, I've moved from a hybrid app to a full microservices so I don't have this issue, or a repro, any longer. If you cannot reproduce it then it was probably something in my code. I suggest closing the issue and re-visiting if it gets reported again.
